name: Creación de nueva release
on: [workflow_dispatch]
env:
  REMOTE_BRANCH: release
  REGISTRY: ghcr.io

jobs:
  create-tag-release:
    name: Creación del nuevo tag y release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.value }}
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - name: Descarga del fichero de versión
        run: wget https://raw.githubusercontent.com/TaixMiguel/Congatudo/${{ env.REMOTE_BRANCH }}/package.json

      - uses: sergeysova/jq-action@v2
        name: Obtención de la versión
        id: version
        with:
          cmd: 'jq .version package.json -r'

      - name: Obtención de la matriz de plataformas Docker
        id: matrix
        run: |
          wget https://raw.githubusercontent.com/TaixMiguel/Congatudo/${{ env.REMOTE_BRANCH }}/matrix.json
          echo "::set-output name=matrix::$(jq -c . matrix.json)"

      - uses: rickstaa/action-create-tag@v1
        name: Creación del tag
        with:
          tag: ${{ steps.version.outputs.value }}
          message: Tag ${{ steps.version.outputs.value }}

      - name: Creación de la release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.value }}
          release_name: ${{ steps.version.outputs.value }}
          draft: false
          prerelease: false
  
  build-packages:
    name: Generación del paquete asociado a la release
    needs: create-tag-release
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.create-tag-release.outputs.matrix) }}
    steps:      
      - name: Inicio de sesión Docker
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construcción y subida de la imagen (amd64)
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/taixmiguel/congatudo-test:${{ needs.create-tag-release.outputs.version }}
            ${{ env.REGISTRY }}/taixmiguel/congatudo-test:dev
          build-args: |
            "BUILD_FROM=${{ matrix.build_from }}"
            "PKG_TARGET=${{ matrix.pkg_target }}"
            "PKG_OPTIONS=${{ matrix.pkg_options }}"
